# Generated by Django 5.1.5 on 2025-01-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('lecture_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lecture_name', models.CharField(max_length=200)),
                ('professor_id', models.IntegerField()),
                ('is_online', models.BooleanField()),
                ('prerequisite', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
